// <auto-generated/>
// TODO (Cameron): Not auto generated. Remove when this issue is addressed: https://github.com/dotnet/roslyn/issues/3705

// Copyright (c) Brock Allen & Dominick Baier. All rights reserved.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.
// Modifications copyright (c) Lykke Corp.

namespace Ironclad.Middleware
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text.Encodings.Web;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authentication;
    using Microsoft.AspNetCore.Authentication.OpenIdConnect;
    using Microsoft.AspNetCore.Http;
    using Microsoft.Extensions.Logging;
    using Microsoft.Extensions.Options;

    internal class ExternalIdentityProviderAuthenticationHandlerProvider : IAuthenticationHandlerProvider
    {
        private readonly Dictionary<string, IAuthenticationHandler> handlers = new Dictionary<string, IAuthenticationHandler>(StringComparer.Ordinal);

        private readonly IAuthenticationHandlerProvider provider;
        private readonly IAuthenticationSchemeProvider schemes;
        private readonly IStore<ExternalIdentityProvider> store;
        private readonly IPostConfigureOptions<OpenIdConnectOptions> configureOptions;
        private readonly ILoggerFactory logger;
        private readonly HtmlEncoder htmlEncoder;
        private readonly UrlEncoder encoder;
        private readonly ISystemClock clock;

        public ExternalIdentityProviderAuthenticationHandlerProvider(
            Decorator<IAuthenticationHandlerProvider> decorator,
            Decorator<IAuthenticationSchemeProvider> schemes,
            IStore<ExternalIdentityProvider> store,
            IPostConfigureOptions<OpenIdConnectOptions> configureOptions,
            ILoggerFactory logger,
            HtmlEncoder htmlEncoder,
            UrlEncoder encoder,
            ISystemClock clock)
        {
            this.provider = decorator.Instance;
            this.schemes = schemes.Instance;
            this.store = store;
            this.configureOptions = configureOptions;
            this.logger = logger;
            this.htmlEncoder = htmlEncoder;
            this.encoder = encoder;
            this.clock = clock;
        }

        public async Task<IAuthenticationHandler> GetHandlerAsync(HttpContext context, string authenticationScheme)
        {
            if (this.handlers.TryGetValue(authenticationScheme, out var handler))
            {
                return handler;
            }

            var matchedScheme = await this.schemes.GetSchemeAsync(authenticationScheme);
            if (matchedScheme != null)
            {
                handler = await this.provider.GetHandlerAsync(context, authenticationScheme);
                if (handler != null)
                {
                    return handler;
                }

                return null;
            }

            var identityProvider = this.store.Query.SingleOrDefault(provider => provider.AuthenticationScheme == authenticationScheme);
            if (identityProvider == null)
            {
                return null;
            }

            var options = identityProvider.PreConfiguredOptions;
            this.configureOptions.PostConfigure(identityProvider.AuthenticationScheme, options);
            var optionsMonitor = new StaticOptionsMonitor(options);

            handler = new OpenIdConnectHandler(optionsMonitor, this.logger, this.htmlEncoder, this.encoder, this.clock);

            var scheme = new AuthenticationScheme(identityProvider.AuthenticationScheme, identityProvider.DisplayName, typeof(OpenIdConnectHandler));
            await handler.InitializeAsync(scheme, context);

            this.handlers[authenticationScheme] = handler;

            return handler;
        }
    }
}