// <auto-generated />
using Ironclad.ExternalIdentityProvider;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ironclad.ExternalIdentityProvider.Migrations
{
    [DbContext(typeof(ExternalProviderContext))]
    [Migration("20181123113417_AddExternalProviders")]
    partial class AddExternalProviders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Ironclad.ExternalIdentityProvider.Persistence.IdentityProvider", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Authority");

                    b.Property<string>("CallbackPath");

                    b.Property<string>("ClientId");

                    b.Property<string>("DisplayName");

                    b.HasKey("Name");

                    b.ToTable("ExternalIdentityProviders");
                });
#pragma warning restore 612, 618
        }
    }
}
